# Generated by Django 5.2 on 2025-04-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usertoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_assign_user_role', 'Can assign USER role to users')]},
        ),
    ]
