# Generated by Django 5.2 on 2025-04-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_users', 'Can manage regular users'), ('can_promote_to_teacher', 'Can promote users to teacher role')]},
        ),
    ]
